---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgen-openshift-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: stackgen-demo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: iac/helm/stackgen-openshift-demo
    repoURL: 'https://github.com/jamesfalkner/todo-demo-app'
    targetRevision: HEAD

