apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quarkus-stackgen-build-trigger-template
  labels:
    app: quarkus-stackgen
spec:
  params:
    - name: git-repository-url
      default: "https://github.com/jamesfalkner/todo-demo-app.git"
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: quarkus-stackgen-build-pipeline-
      spec:
        pipelineRef:
          name: quarkus-stackgen-build-pipeline
        params:
          - name: git-repository-url
            value: $(tt.params.git-repository-url)
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
          - name: maven-settings
            emptyDir: {}
